{% set data= load_setup_py_data() %}
package:
  name: "ts-ess-csc"
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: generic
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - run_ess_csc = lsst.ts.ess.csc.cli:execute_csc
  script_env:
    - PATH
    - LD_LIBRARY_PATH
    - OSPL_HOME
    - PYTHON_BUILD_LOCATION
    - LSST_DDS_PARTITION_PREFIX
    - TS_CONFIG_OCS_DIR

test:
  requires:
    - ts-conda-build =0.3
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
    - ts-tcpip
    - ts-ess-common
    - ts-dds
    - pyserial
    - pyftdi
  source_files:
    - python
    - bin
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - py.test

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
  build:
    - python {{ python }}
    - setuptools_scm
    - setuptools
    - ts-conda-build =0.3
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - ts-idl
    - ts-salobj
    - ts-tcpip
    - ts-ess-common
